parent_config: ['./conf/nli/esim.yaml', './conf/nli/multinli/abstract_multinli.yaml']

# fixed experiment seed
seed: 1337
dropout: 0.2
repr_dim: 300
validation_interval: 2000
learning_rate: 0.0004
learning_rate_decay: 1.0
batch_size: 32
epochs: 10
